version: "2"

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  osem:
    build:
      context: .
      args:
        CONTAINER_USERID: 1000
    command: /osem/bin/osem-init.sh
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/osem
